# Generated by Django 2.2.5 on 2019-12-14 02:36

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(max_length=5000)),
                ('specification', tinymce.models.HTMLField(blank=True, verbose_name='Specification')),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='store/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('label', models.CharField(blank=True, choices=[('PR', 'prefered'), ('MO', 'most viewed'), ('SA', 'sale')], max_length=2)),
                ('label_bg', models.CharField(blank=True, choices=[('PR', 'primary'), ('SE', 'secondary'), ('DA', 'danger'), ('IN', 'info')], max_length=2)),
                ('category', models.CharField(blank=True, choices=[('TS', 'Shirt'), ('PA', 'Pants'), ('UN', 'Underware'), ('SH', 'Shoe')], max_length=2)),
                ('sold', models.PositiveIntegerField(blank=True, default='0', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('product', models.ManyToManyField(related_name='product', to='store.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Product')),
            ],
        ),
    ]
