# Generated by Django 2.2.6 on 2020-02-03 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_seller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='item',
            new_name='name',
        ),
    ]
